# 数据目录
paper_directory:
  data_root: 'data/papers'
  pdf_path: 'document'
  md_path: 'output/markdown'
  xml_path: 'output/xml'
  sqlite_path: 'sqlite/document.db'

# 登录系统相关
user_login_config:
  user_root: "data/user"
  sqlite_filename: "user_info.db"

  # 系统初始化的管理员账户信息
  admin_user:
    username: "admin"       # 管理员用户名
    password: "admin123"    # 管理员密码

# 配置代理
proxy:
  type: 'http' # http或socks5
  host: '127.0.0.1'
  port: 1080

retrieve:
  milvus:
    milvus_host: '127.0.0.1'
    milvus_port: 19530
    using_remote: False
    remote_database:
      url: ''
      username: ''
      password: ''

  embedding:
    model: 'BAAI/bge-m3'
    save_local: True
    fp16: True
    normalize: True
    device: 'cuda'

  reranker:
    model: 'BAAI/bge-reranker-v2-m3'
    save_local: True
    fp16: True
    normalize: True
    device: 'cuda'

llm:
  openai:
    use_proxy: True
    api_key: ''

  zhipu:
    model: 'glm-4-flash'
    api_key: ''

tools:
  pubmed:
    use_proxy: True
    api_key: ''

  serper:
    use_proxy: True
    api_key: ''

  grobid:
    grobid_server: 'http://localhost:8070'
    service: 'processFulltextDocument'
    batch_size: 100
    sleep_time: 5
    timeout: 5
    coordinates:
      - 'persName'
      - 'ref'
      - 'head'
      - 's'
      - 'p'
      - 'title'
    multi_process: 10