# 数据目录
data_root: 'data'
pdf_path: 'document'
md_path: 'output/markdown'
xml_path: 'output/xml'

# 配置代理
proxy:
  type: 'http' # http或socks5
  host: '127.0.0.1'
  port: 1080

auth:
  admin_token: 'admin'
  owner_token: 'owner'

# NCBI相关
pubmed:
  use_proxy: True
  api_key: ''

# grobid相关配置
grobid:
  config_path: 'grobid/grobid.json'
  service: 'processFulltextDocument'
  multi_process: 10

# milvus
milvus:
  milvus_host: '127.0.0.1'
  milvus_port: 19530
  en_model: 'BAAI/bge-large-en-v1.5'
  zh_model: 'DMetaSoul/Dmeta-embedding'
  using_remote: False
  remote_database:
    url: ''
    username: ''
    password: ''

openai:
  use_proxy: True
  api_key: ''