# PDF解析器
pdf_parser: 'grobid'  # grobid or nougat

# 数据目录
pdf_root: 'data/document'
md_output: 'data/output/markdown'
xml_output: 'data/output/xml'

# 配置代理
proxy:
  type: 'http' # http或socks5
  host: '127.0.0.1'
  port: 1080

# NCBI相关
pubmed:
  use_proxy: True
  api_key: ''

# grobid相关配置
grobid:
  config_path: 'grobid/grobid.json'
  service: 'processFulltextDocument'
  multi_process: 10

# milvus
milvus:
  milvus_host: '127.0.0.1'
  milvus_port: 19530
  collection_name: 'document'

openai:
  use_proxy: True
  api_key: ''