# 数据目录
data_root: 'data'
pdf_path: 'document'
md_path: 'output/markdown'
xml_path: 'output/xml'
sqlite_path: 'sqlite/document.db'

# 配置代理
proxy:
  type: 'http' # http或socks5
  host: '127.0.0.1'
  port: 1080

# 身份验证
auth:
  admin_token: 'admin' # admin身份组可以进行文件上传的操作
  owner_token: 'owner' # owner身份组可以进行知识库删改的操作

# NCBI相关
pubmed:
  use_proxy: True
  api_key: ''

# grobid相关配置
grobid:
  config_path: 'grobid/grobid.json'
  service: 'processFulltextDocument'
  multi_process: 10

# milvus
milvus:
  milvus_host: '127.0.0.1'
  milvus_port: 19530
  en_model: 'WhereIsAI/UAE-Large-V1'
  zh_model: 'infgrad/stella-large-zh-v3-1792d'
  using_remote: False
  remote_database:
    url: ''
    username: ''
    password: ''

llm:
  openai:
    use_proxy: True
    api_key: ''

  claude3:
    use_proxy: True
    model: 'claude-3-opus-20240229'
    api_key: ''