version: '3'
services:
  grobid-gpu:
    image: grobid/grobid:0.8.0
    ports:
      - "8070:8070"
    ulimits:
      core: 0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              device_ids: ["0"]
    restart: on-failure